---
# tasks file for install_apps
- name: install epel
  yum:
    name: epel-release
    state: latest

- name: install java git maven wget nrpe nagios-plugins
  yum:
   name:
    - java-1.8.0-openjdk
    - maven
    - git
    - wget
    - nrpe
    - nagios-plugins
   state: latest



