---
# tasks file for install_Splunk_server
- name: Download splunk forwarde
  get_url:
    url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.1.2&product=universalforwarder&filename=splunkforwarder-8.1.2-545206cc9f70-Linux-x86_64.tgz&wget=true'
    dest: /opt/splunk-8.1.2.tgz

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /opt/splunk-8.1.2.tgz
    dest: /opt/
    remote_src: yes

- name: write user-seed.conf
  template:
    src:   user-seed.conf
    dest:  /opt/splunk/etc/system/local/user-seed.conf

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/splunkforwarder
    state: directory
    recurse: yes
    mode: '777'

- name: splunk start
  command: './splunk start --accept-license --no-prompt chdir=/opt/splunkforwarder/bin'
